### ISSUE TITLE
Suggestions on how to get the docs as EPUB or MOBI

### ISSUE THREAD

**Issue by dhoerlST** [SwiftDocOrg/swiftdoc.org#10]
I'd love to have this documentation available on an Kindle - when outside in the Summer. I tried using 'calibre' with a starting point of the index.html file in the '_site' folder. It converts the pages to an EPUB, but the links are not clickable. [Once turned into an EPUB, you can look at the file in iBooks]

I just tried opening that file with Safari, and when you click on a link you see "No file Exists at /Global"

**Comment by natecook1000** [comment]
Hi, @dhoerlST, thanks for the question. Unfortunately that's outside the scope of SwiftDoc—you might want to try Dash, which includes this documentation and has both a Mac and iOS client.
