### ISSUE TITLE
String.unicodeScalars incorrectly claims there's no setter

### ISSUE THREAD

**Issue by kballard** [SwiftDocOrg/swiftdoc.org#11]
The documentation for `String.unicodeScalars` declares the property with only a getter. This is incorrect, the variable has both a getter and a setter.

**Comment by natecook1000** [comment]
Thanks for this! This showed up when variables were declared without the `{ get set }` that usually appears for (what must be) computed properties. Fixed in https://github.com/SwiftDocOrg/swiftdoc-parser/commit/bedf362189ef94dc94db44c69e6784bd6d3487db.
