### ISSUE TITLE
Switching between swift version should show the current selection

### ISSUE THREAD

**Issue by masters3d** [SwiftDocOrg/swiftdoc.org#15]
The swift version selection should be able to switch between the current selected version and the new one

![image](https://cloud.githubusercontent.com/assets/6539412/8639781/654ea2f2-2898-11e5-8f71-bf60b22d81db.png)

For example if I am at
http://swiftdoc.org/swift-2/type/ArraySlice/

Clicking on v.1.2 should take me to 
http://swiftdoc.org/type/ArraySlice/  or 
http://swiftdoc.org/swift-1_2/type/ArraySlice/

not http://swiftdoc.org or http://swiftdoc.org/swift-2

Thanks for the great resource by the way.

**Comment by natecook1000** [comment]
Thanks for the suggestion, @masters3d — this is in as of b7f3e04b8422bdd220e69e8043dc88e92fbb84f4. Let me know if you see anything out of the ordinary!

**Comment by masters3d** [comment]
Looks good! Thank you for implementing.
