### ISSUE TITLE
There’s a problem with enum case names

### ISSUE THREAD

**Issue by dabrahams** [SwiftDocOrg/swiftdoc.org#17]
See for example http://swiftdoc.org/v2.0/type/PlaygroundQuickLook/

    case RectangleFloat64, Float64, Float64, Float64

**Comment by dabrahams** [comment]
I guess it’s pasting the type names in the payload to the back of the case name.  There should be parens around the payload, too

**Comment by natecook1000** [comment]
Thanks, @dabrahams! :tada:
