### ISSUE TITLE
Can't link to a specific overload of a function

### ISSUE THREAD

**Issue by ole** [SwiftDocOrg/swiftdoc.org#18]
The element IDs of functions are based on the function’s name but not their exact signature, which means if a function has multiple overloads you can't link to a specific variant. Example: [`print`](http://swiftdoc.org/v2.0/func/print/) has two overloads, and they both look like this:

```html
<div class="declaration" id="func-print">…</div>
<div class="declaration" id="func-print">…</div>
```

**Comment by natecook1000** [comment]
Thanks, @ole! One complicating factor is that it needs to be able to disambiguate a function that might be declared as part of a protocol and then also appear once or more in the default implementations section. 

`SequenceType`, for example, declares `func generate() -> Self.Generator`, and then supplies two (conditional) default implementations. I'd like those IDs to be as stable across releases as possible, so they would probably need to incorporate the where clause of an extension.

**Comment by natecook1000** [comment]
Hi @ole — I think this is resolved now with the site revision. Can you check on your end?

**Comment by ole** [comment]
@natecook1000 Looks great! Thanks for the work you put into this.
