### ISSUE TITLE
No such file or directory: assets/js/swift-linkdata.js

### ISSUE THREAD

**Issue by mr16839072** [SwiftDocOrg/swiftdoc.org#20]
Followed the build process on the readme and got the following errors, any ideas?

	08:40:59 web.1  | started with pid 69404
	08:41:00 web.1  | Configuration file: /Users/markrobinson/Developer/swift/swiftdoc.org/_config.yml
	08:41:00 web.1  | /Users/markrobinson/Developer/swift/swiftdoc.org/_plugins/archive_gen.rb:72: warning: already initialized constant Jekyll::MonthlyArchivePage::ATTRIBUTES_FOR_LIQUID
	08:41:00 web.1  | /Users/markrobinson/Developer/swift/swiftdoc.org/_plugins/_site/archive_gen.rb:72: warning: previous definition of ATTRIBUTES_FOR_LIQUID was here
	08:41:00 web.1  |             Source: /Users/markrobinson/Developer/swift/swiftdoc.org
	08:41:00 web.1  |        Destination: /Users/markrobinson/Developer/swift/swiftdoc.org/_site
	08:41:00 web.1  |       Generating...
	08:41:00 web.1  | Asset Pipeline: Processing 'css_asset_tag' manifest 'swift'
	08:41:00 web.1  | Asset Pipeline: Saved 'swift-179e571a6c370721b5fed515a6c032dd.css' to '/Users/markrobinson/Developer/swift/swiftdoc.org/_site/assets'
	08:41:00 web.1  | Asset Pipeline: Failed to generate hash from provided manifest: No such file or directory @ rb_file_s_mtime - /Users/markrobinson/Developer/swift/swiftdoc.org/assets/js/swift-linkdata.js
	08:41:00 web.1  |   Liquid Exception: No such file or directory @ rb_file_s_mtime - /Users/markrobinson/Developer/swift/swiftdoc.org/assets/js/swift-linkdata.js in _includes/head.html, included in _layouts/wrapper.html
	08:41:00 web.1  | jekyll 2.5.3 | Error:  No such file or directory @ rb_file_s_mtime - /Users/markrobinson/Developer/swift/swiftdoc.org/assets/js/swift-linkdata.js
	08:41:00 web.1  | exited with code 1
	08:41:00 system | sending SIGTERM to all processes

**Comment by natecook1000** [comment]
I think that file gets generated by [swiftdoc-parser](https://github.com/SwiftDocOrg/swiftdoc-parser) along with the rest of the documentation — if you're doing something where you don't need it you could drop in a blank file.
