### ISSUE TITLE
Search API doesn't return results for many queries

### ISSUE THREAD

**Issue by mattrajca** [SwiftDocOrg/swiftdoc.org#24]
While search on the swiftdoc.org website returns search results for queries such as 'distanceTo', the API returns an empty array:

http://api.swiftdoc.org/search?q=distanceto

**Comment by natecook1000** [comment]
Hi @mattrajca—the API isn't under active development and its data had gotten vastly out of date. I've updated the data to Swift 2.1, but it looks like there are still issues with it that I won't have time to get into soon. I've pushed the API repo up to GitHub, you can take a look here: https://github.com/SwiftDocOrg/api.swiftdoc.org

**Comment by natecook1000** [comment]
@mattrajca Okay, I've updated the API :laughing: — search away!
