### ISSUE TITLE
[Suggestion] allow jumping between hierarchy views 

### ISSUE THREAD

**Issue by masters3d** [SwiftDocOrg/swiftdoc.org#25]
Inside the hierarchy view I'd like to jump to other hierarchy 
views I click, instead of going back to the detail description. 
For example:
http://swiftdoc.org/v2.1/type/String/hierarchy/
The gray boxes should take me to another hierarchy view
The current/red box functionality should stay the same (detail description). 

Thanks!

**Comment by natecook1000** [comment]
Of course, that's how it should have worked all along! :facepalm:

**Comment by masters3d** [comment]
ah cool!

**Comment by natecook1000** [comment]
Implemented in https://github.com/SwiftDocOrg/swiftdoc-parser/commit/fe45d094137e1c8656344820fcf682a8cf13c084. Thanks again, @masters3d! :tada:
