### ISSUE TITLE
Include Compiler Control Statements

### ISSUE THREAD

**Issue by dastrobu** [SwiftDocOrg/swiftdoc.org#26]
Compiler control statements such as the build configuration statements  `#if`, `#endif` including the functions `os()` and `arch()` seem to be missing from the documentation.

**Comment by natecook1000** [comment]
Hi @dastrobu, thanks for coming by! SwiftDoc.org is focused on the standard library only, so compiler-related statements like those aren't in scope for the project. Those are fully documented in the [Swift Language Reference](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Statements.html#//apple_ref/swift/grammar/compiler-control-statement) if you need more info.
