### ISSUE TITLE
3.0 API is out of date: No updates to site since June 18 2016

### ISSUE THREAD

**Issue by snej** [SwiftDocOrg/swiftdoc.org#27]
I love the site, but it's become troublesome to use it for Swift 3.0 code because it's missing a lot of the recent API changes. From the [commit log](https://github.com/SwiftDocOrg/SwiftDocOrg.github.io/commits/master) it appears the website hasn't been updated since June 18, i.e. 2 ½ months ago. Is there going to be an update soon, or is the site on hiatus and I should look elsewhere for my documentation needs?

**Comment by mattt** [comment]
I'm happy to report that SwiftDoc is now updated for Swift 4.2. We're still waiting for DNS to be updated; in the meantime, you can access it here: https://swiftdoc.netlify.com.

For more details, please see #32.
