### ISSUE TITLE
API for swiftdoc.org

### ISSUE THREAD

**Issue by kareman** [SwiftDocOrg/swiftdoc.org#3]
I would like to create an OS X service which opens up the corresponding page on swiftdoc.org when I right click on an identifier from the swift standard library and select the service from the menu. The “Quick Help” panel in Xcode often doesn't show anything, and in any case this site is far easier to explore.

It would be nice to be able to just go `swiftdoc.org/{identifier}` or have a JSON/XML file with all the identifiers and links to their pages. I could of course just scrape index.html but it would be best to have an official way of doing it.

**Comment by natecook1000** [comment]
@kareman, I agree completely. An API is definitely on the docket, but I have a little refactoring to do first to decouple the parser from the scripts that build the static site. I'll work on getting that done and the API up.

**Comment by natecook1000** [comment]
@kareman Okay, very alpha API is up -- what do you think?

http://api.swiftdoc.org/

**Comment by kareman** [comment]
Excellent, this looks very good, I'm looking forward to trying this out later today.
