### ISSUE TITLE
Update to Swift 3.1 (Xcode 8.3)

### ISSUE THREAD

**Issue by Kapeli** [SwiftDocOrg/swiftdoc.org#30]
Will the docs be updated to Swift 3.1 (Xcode 8.3)? Or is Xcode 8.3b2 the same as the final Xcode 8.3?

Thank you!

**Comment by mattt** [comment]
I'm happy to report that SwiftDoc is now updated for Swift 4.2. We're still waiting for DNS to be updated; in the meantime, you can access it here: https://swiftdoc.netlify.com.

For more details, please see #32.
