### ISSUE TITLE
Swift 4 Support

### ISSUE THREAD

**Issue by philosopherdog** [SwiftDocOrg/swiftdoc.org#32]
Swift 4 support please.

**Comment by strangemonad** [comment]
@natecook1000 curious if there’s any update on this? I’d love to see continued support for swift documentation that’s separate from the developer.apple.com docs

**Comment by mattt** [comment]
I'm happy to report that SwiftDoc is now updated for Swift 4.2. We're still waiting for DNS to be updated; in the meantime, you can access it here: https://swiftdoc.netlify.com

Thanks for your patience on this, everyone. My goal is to make SwiftDoc sustainable for the long term, with regular updates with each language release. Once that's in place, I'm excited to look into how we can make the site even more useful to developers.
