### ISSUE TITLE
Not loading CSS or JavaScript when on subpath.

### ISSUE THREAD

**Issue by kareman** [SwiftDocOrg/swiftdoc.org#6]
See http://kareman.github.io/swiftdoc.org/ 

I [cloned](https://github.com/kareman/swiftdoc.org) this repository, [changed the url setting in the config file](https://github.com/kareman/swiftdoc.org/commit/e35dce3c41404d6cb22d35f283e71821b88b7ab7), built the site with Jekyll and pushed it to the [gh-pages](https://github.com/kareman/swiftdoc.org/tree/gh-pages) branch of the clone.

I think the solution is to add baseurl to _config.yml  as recommended in http://jekyllrb.com/docs/github-pages/ , and then update _includes/head.html (amongst others) to use the
“baseurl” setting, not "url".

**Comment by kareman** [comment]
@natecook1000 
I think the problem lies in https://github.com/SwiftDocOrg/swiftdoc.org/blob/master/_plugins/jekyll_asset_pipeline.rb#L20 and https://github.com/SwiftDocOrg/swiftdoc.org/blob/master/_plugins/jekyll_asset_pipeline.rb#L25 .

I've tried
 ```ruby
      "<link href=\"#{site.baseurl}/#{@path}/#{@filename}\" rel=\"stylesheet\" type=\"text/css\" />"
 ```

, #{@site.baseurl} and #{@baseurl} but no luck.

The settings are:

```yaml
baseurl:            "/swiftdoc.org"
url:                "http://kareman.github.io"
```

**Comment by kareman** [comment]
I worked around the problem by not using jekyll_asset_pipeline, see https://github.com/kareman/swiftdoc.org/tree/enable-site-in-sub-path . The result can be seen [here](http://kareman.github.io/swiftdoc.org/). It looks good, but none of the links work because the parser makes them absolute (and obviously has no idea about the baseURL).

One solution is to make all the links relative (remove the leading "/") and use a `<base>` tag in `<head>`.

**Comment by kareman** [comment]
I tried passing the parameter `--url-prefix  ""` to the parser but it doesn't seem to have any effect.

**Comment by natecook1000** [comment]
Sorry to leave you hanging on this one, @kareman—the real solution to this is to move from having the parser generate HTML that lives in the Jekyll instance to having it generate a simple data format that Jekyll can parse and render in its own templates. Then there'd be a single source of configuration. I've been too busy to get to that, but it's on my list—hopefully I'll have time to take care of it soon.

**Comment by kareman** [comment]
Hey no problem, I knew you were busy with [this](http://nshipster.com), amongst other things.

A better separation between the parser and the website seems like a good idea; the parser can already output JSON, presumably Jekyll will turn that into the website. Looking forward to it.
